Repository noteezy/LECHO, pull requests merged in 2020-03, with the labels that each got.

#16 fixes minor problems w/ use cases
  docs/UseCases.pdf
  docs/sources/GuestUseCase.uxf
  docs/sources/SubjetManagement.uxf
  docs/sources/UseCases.docx
Labels: bug, documentation

#17 Seq deg
  docs/functional_requirements.pdf
  docs/sources/Sequence_diagram.png
  docs/sources/functional_requirements.docx
  docs/sources/sequence_diagram.uxf
Labels: bug, documentation

#18 Renamed files + file with all Docs
  docs/ClassDiagram.pdf
  docs/Documentation.pdf
  docs/FunctionalRequirements.pdf
  docs/NonFunctionalRequirements.pdf
  docs/Requirements.pdf
  docs/SequenceDiagram.pdf
  docs/sources/ClassDiagram.docx
  docs/sources/ClassDiagram.png
  docs/sources/FunctionalRequirements.docx
  docs/sources/NonFunctionalRequirements.docx
  docs/sources/Requirements.docx
  docs/sources/SequenceDiagram.docx
  docs/sources/SequenceDiagram.png
  docs/sources/SequenceDiagram.uxf
  docs/sources/SubjectManagement.uxf
Labels: documentation

#20 Added page with potential choices and profile page
  docs/Mockups.pdf
  docs/sources/MockupDescriptionPage.png.png
  docs/sources/MockupLoginPage.png
  docs/sources/MockupMainPage.png
  docs/sources/MockupPotentialChoicePage.png.png
  docs/sources/MockupProfilePage.png.png
Labels: visualisation

#28 DB filling
  src/LECHO.sql
Labels: implemantation

#41 Origin/sonya
  src/.vs/LECHO/DesignTimeBuild/.dtbcache.v2
  src/.vs/LECHO/config/applicationhost.config
  src/LECHO.Core/AccountManagement.cs
  src/LECHO.Infrastructure/LECHOContext.cs
  src/LECHO.Web/Controllers/SubjectsController.cs
  src/LECHO.Web/Views/Shared/_Layout.cshtml
  src/LECHO.Web/Views/Shared/_LayoutAdmin.cshtml
  src/LECHO.Web/Views/Shared/_LayoutLecturer.cshtml
  src/LECHO.Web/Views/Shared/_LayoutStudent.cshtml
  src/LECHO.Web/Views/Subjects/SubjectsFirstTerm.cshtml
  src/LECHO.Web/Views/Subjects/SubjectsSecondTerm.cshtml
  src/LECHO.Web/wwwroot/css/site.css
Labels: Code

#42 Header style
  src/.vs/LECHO/config/applicationhost.config
  src/.vs/LECHO/v16/Server/sqlite3/storage.ide-shm
  src/.vs/LECHO/v16/Server/sqlite3/storage.ide-wal
  src/LECHO.Infrastructure/LECHOContext.cs
  src/LECHO.Web/Views/Shared/_Layout.cshtml
  src/LECHO.Web/Views/Shared/_LayoutAdmin.cshtml
  src/LECHO.Web/Views/Shared/_LayoutLecturer.cshtml
  src/LECHO.Web/Views/Shared/_LayoutStudent.cshtml
  src/LECHO.Web/wwwroot/css/site.css
Labels: Code, bug

#43 Origin/sonya
  src/.vs/LECHO/config/applicationhost.config
  src/LECHO.Core/SubjectManagement.cs
  src/LECHO.Infrastructure/LECHOContext.cs
  src/LECHO.Web/Controllers/SubjectsController.cs
  src/LECHO.Web/Views/Shared/_Layout.cshtml
  src/LECHO.Web/Views/Subjects/SubjectsFirstTerm.cshtml
  src/LECHO.Web/Views/Subjects/SubjectsSecondTerm.cshtml
  src/LECHO.Web/wwwroot/css/site.css
Labels: Code
